import { Translations, Product, Language } from './types';

// --- APP CONFIGURATION ---
export const APP_CONFIG = {
  // ÖNEMLİ: C:\Users\... gibi yerel dosya yolları web sitelerinde ÇALIŞMAZ.
  // Logonuzu bir yere yükleyip (hizliresim, imgur vb.) https:// ile başlayan linki buraya yapıştırmalısınız.
  // Şimdilik örnek olması için internetten bir logo linki koyuyorum:
  logoUrl: 'https://cdn-icons-png.flaticon.com/512/3081/3081559.png', 
  
  // Admin Giriş Bilgileri
  adminUsername: 'cynx0110',
  adminPassword: 'Kesha.com.04' 
};

export const TRANSLATIONS: Record<Language, Translations> = {
  ru: {
    home: 'Главная',
    cart: 'Корзина',
    admin: 'Админ',
    settings: 'Настройки',
    featured: 'Рекомендуем',
    addToCart: 'В корзину',
    buyNow: 'Купить сейчас',
    description: 'Описание',
    delivery: 'Доставка',
    price: 'Цена',
    total: 'Итого',
    checkout: 'Оформить заказ',
    contact: 'Контакты',
    language: 'Язык',
    addProduct: 'Добавить товар',
    editProduct: 'Редактировать товар',
    update: 'Обновить',
    cancel: 'Отмена',
    title: 'Название',
    image: 'Изображение',
    category: 'Категория',
    save: 'Сохранить',
    delete: 'Удалить',
    days: 'дней',
    orderHistory: 'История заказов',
    emptyCart: 'Корзина пуста',
    uploadPhoto: 'Загрузить фото',
    orUrl: 'Или ссылка на фото',
    adminPanel: 'Панель админа',
    products: 'Товары',
    orders: 'Заказы',
    images: 'Фотографии',
    sizes: 'Размеры / Варианты',
    addSize: 'Добавить размер',
    selectSize: 'Выберите размер',
    selectCategory: 'Выберите категорию',
    sizeRequired: 'Пожалуйста, выберите размер',
    shippingRates: 'Тарифы на доставку',
    airCargo: 'Авиа (Howa) - 7-15 дней',
    roadCargo: 'Наземный (Gara) - 25-30 дней',
    expressCargo: 'Экспресс Авиа - 5-7 дней',
    contactUs: 'Свяжитесь с нами',
    orderVia: 'Заказать через',
    followUs: 'Подписаться',
    personalAccount: 'Личный аккаунт',
    copyNumber: 'Скопировать номер',
    copied: 'Скопировано!',
    status: 'Статус',
    date: 'Дата',
    items: 'Товары',
    noOrders: 'Нет заказов',
    orderDetails: 'Детали заказа',
    myOrders: 'Мои заказы',
    trackOrder: 'Отследить заказ',
    st_pending: 'Заказ создан',
    st_processing: 'На складе в Пекине',
    st_shipped: 'Отправлен в ТМ',
    st_arrived: 'Прибыл в ТМ',
    st_delivered: 'Доставлен клиенту',
    updateStatus: 'Обновить статус',
    weight: 'Вес',
    shippingCost: 'Стоимость доставки',
    enterWeightPrice: 'Введите вес и цену доставки',
    productTotal: 'Сумма товаров',
    grandTotal: 'Общая сумма',
    kg: 'кг',
    setDetails: 'Установить',
    login: 'Войти',
    signup: 'Регистрация',
    logout: 'Выйти',
    username: 'Имя пользователя',
    password: 'Пароль',
    phone: 'Телефон',
    email: 'Email',
    fullName: 'Имя Фамилия',
    customerID: 'ID Клиента',
    welcome: 'Добро пожаловать',
    adminLogin: 'Вход для админа',
    customerLogin: 'Вход для клиента',
    loginError: 'Неверные данные',
    fillAllFields: 'Заполните все поля',
    yourId: 'Ваш ID',
    enterCustomerId: 'Введите номер клиента (5 цифр)',
    createPassword: 'Придумайте пароль',
    registrationSuccess: 'Регистрация успешна!',
    saveYourId: 'Сохраните ваш номер клиента, он нужен для входа:',
    loginToContinue: 'Войти',
    userNotFound: 'Пользователь не найден',
    sendCode: 'Отправить код',
    enterCode: 'Введите код',
    verify: 'Подтвердить',
    wrongCode: 'Неверный код',
    codeSentTo: 'Код отправлен на',
    resend: 'Отправить снова',
    confirmPassword: 'Подтвердите пароль',
    passwordMismatch: 'Пароли не совпадают',
  },
  tr: {
    home: 'Ana Sayfa',
    cart: 'Sepet',
    admin: 'Yönetici',
    settings: 'Ayarlar',
    featured: 'Öne Çıkanlar',
    addToCart: 'Sepete Ekle',
    buyNow: 'Hemen Al',
    description: 'Açıklama',
    delivery: 'Teslimat',
    price: 'Fiyat',
    total: 'Toplam',
    checkout: 'Siparişi Tamamla',
    contact: 'İletişim',
    language: 'Dil',
    addProduct: 'Ürün Ekle',
    editProduct: 'Ürünü Düzenle',
    update: 'Güncelle',
    cancel: 'İptal',
    title: 'Başlık',
    image: 'Görsel',
    category: 'Kategori',
    save: 'Kaydet',
    delete: 'Sil',
    days: 'gün',
    orderHistory: 'Sipariş Geçmişi',
    emptyCart: 'Sepetiniz boş',
    uploadPhoto: 'Fotoğraf Yükle',
    orUrl: 'Veya görsel linki',
    adminPanel: 'Yönetici Paneli',
    products: 'Ürünler',
    orders: 'Siparişler',
    images: 'Görseller',
    sizes: 'Bedenler / Boyutlar',
    addSize: 'Beden Ekle',
    selectSize: 'Beden Seçin',
    selectCategory: 'Kategori Seçin',
    sizeRequired: 'Lütfen bir beden seçiniz',
    shippingRates: 'Kargo Ücretleri',
    airCargo: 'Hava Yolu (Howa) 7-15 gün',
    roadCargo: 'Kara Yolu (Gara) 25-30 gün',
    expressCargo: 'Express Hava 5-7 gün',
    contactUs: 'Bize Ulaşın',
    orderVia: 'Sipariş Ver',
    followUs: 'Takip Et',
    personalAccount: 'Kişisel Hesap',
    copyNumber: 'Numarayı Kopyala',
    copied: 'Kopyalandı!',
    status: 'Durum',
    date: 'Tarih',
    items: 'Ürünler',
    noOrders: 'Henüz sipariş yok',
    orderDetails: 'Sipariş Detayı',
    myOrders: 'Siparişlerim',
    trackOrder: 'Kargo Takip',
    st_pending: 'Sipariş Verildi',
    st_processing: 'Pekin Deposunda',
    st_shipped: 'Kargoya Verildi',
    st_arrived: 'Türkmenistan Deposunda',
    st_delivered: 'Teslim Edildi',
    updateStatus: 'Durumu Güncelle',
    weight: 'Ağırlık',
    shippingCost: 'Kargo Ücreti',
    enterWeightPrice: 'Ağırlık ve Kargo Ücreti Girin',
    productTotal: 'Ürün Toplamı',
    grandTotal: 'Genel Toplam',
    kg: 'kg',
    setDetails: 'Kaydet',
    login: 'Giriş Yap',
    signup: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    username: 'Kullanıcı Adı',
    password: 'Şifre',
    phone: 'Telefon Numarası',
    email: 'E-posta',
    fullName: 'Ad Soyad',
    customerID: 'Müşteri No',
    welcome: 'Hoşgeldiniz',
    adminLogin: 'Yönetici Girişi',
    customerLogin: 'Müşteri Girişi',
    loginError: 'Hatalı giriş bilgileri',
    fillAllFields: 'Lütfen tüm alanları doldurun',
    yourId: 'Müşteri Numaranız',
    enterCustomerId: 'Müşteri Numarası (5 haneli)',
    createPassword: 'Bir şifre belirleyin',
    registrationSuccess: 'Kayıt Başarılı!',
    saveYourId: 'Giriş yapmak için bu numarayı saklayın:',
    loginToContinue: 'Giriş Yap',
    userNotFound: 'Kullanıcı bulunamadı',
    sendCode: 'Kod Gönder',
    enterCode: 'Onay Kodu',
    verify: 'Onayla',
    wrongCode: 'Hatalı Kod',
    codeSentTo: 'Kod şuraya gönderildi:',
    resend: 'Tekrar Gönder',
    confirmPassword: 'Şifreyi Onayla',
    passwordMismatch: 'Şifreler eşleşmiyor',
  },
  tm: {
    home: 'Baş Sahypa',
    cart: 'Sebet',
    admin: 'Admin',
    settings: 'Sazlamalar',
    featured: 'Maslahat berilýän',
    addToCart: 'Sebede goş',
    buyNow: 'Häzir al',
    description: 'Düşündiriş',
    delivery: 'Eltip bermek',
    price: 'Bahasy',
    total: 'Jemi',
    checkout: 'Sargyt etmek',
    contact: 'Habarlaşmak',
    language: 'Dil',
    addProduct: 'Haryt goş',
    editProduct: 'Harydy üýtget',
    update: 'Täzele',
    cancel: 'Yza',
    title: 'Ady',
    image: 'Surat',
    category: 'Kategoriýa',
    save: 'Ýatda sakla',
    delete: 'Poz',
    days: 'gün',
    orderHistory: 'Sargyt taryhy',
    emptyCart: 'Sebet boş',
    uploadPhoto: 'Surat Ýükle',
    orUrl: 'Ýa-da surat linki',
    adminPanel: 'Admin paneli',
    products: 'Harytlar',
    orders: 'Sargytlar',
    images: 'Suratlar',
    sizes: 'Ölçegler',
    addSize: 'Ölçeg goş',
    selectSize: 'Ölçeg saýlaň',
    selectCategory: 'Kategoriýa saýlaň',
    sizeRequired: 'Ölçeg saýlamaly',
    shippingRates: 'Kargo Bahalary',
    airCargo: 'Howa ýollary 7-15 gün',
    roadCargo: 'Gara ýollar 25-30 gün',
    expressCargo: 'Express Howa 5-7 gün',
    contactUs: 'Habarlaşmak üçin',
    orderVia: 'Sargyt et',
    followUs: 'Yzarlaň',
    personalAccount: 'Şahsy hasap',
    copyNumber: 'Belgini göçürip al',
    copied: 'Göçürildi!',
    status: 'Ýagdaýy',
    date: 'Sene',
    items: 'Harytlar',
    noOrders: 'Sargyt ýok',
    orderDetails: 'Sargyt barada',
    myOrders: 'Sargytlarym',
    trackOrder: 'Yzarla',
    st_pending: 'Sargyt edildi',
    st_processing: 'Pekin ammarynda',
    st_shipped: 'Ýola çykdy',
    st_arrived: 'Türkmenistana geldi',
    st_delivered: 'Gowşuryldy',
    updateStatus: 'Ýagdaýy üýtget',
    weight: 'Agramy',
    shippingCost: 'Kargo bahasy',
    enterWeightPrice: 'Agram we Kargo bahasyny giriziň',
    productTotal: 'Haryt jemi',
    grandTotal: 'Umumy jemi',
    kg: 'kg',
    setDetails: 'Tassykla',
    login: 'Giriş',
    signup: 'Agza bol',
    logout: 'Çykmak',
    username: 'Ulanyjy ady',
    password: 'Açar sözi',
    phone: 'Telefon belgisi',
    email: 'E-poçta',
    fullName: 'Ady we Familiýasy',
    customerID: 'Müşderi kody',
    welcome: 'Hoş geldiňiz',
    adminLogin: 'Admin Girişi',
    customerLogin: 'Müşderi Girişi',
    loginError: 'Giriş maglumatlary nädogry',
    fillAllFields: 'Ähli öýjükleri dolduryň',
    yourId: 'Siziň ID',
    enterCustomerId: 'Müşderi kody (5 sanly)',
    createPassword: 'Açar sözüni dörediň',
    registrationSuccess: 'Üstünlikli agza bolduňyz!',
    saveYourId: 'Giriş üçin bu kody ýatda saklaň:',
    loginToContinue: 'Giriş et',
    userNotFound: 'Ulanyjy tapylmady',
    sendCode: 'Kod ugrat',
    enterCode: 'Kody giriz',
    verify: 'Tassykla',
    wrongCode: 'Ýalňyş kod',
    codeSentTo: 'Kod ugradyldy:',
    resend: 'Gaýtadan ugrat',
    confirmPassword: 'Açar sözüni tassykla',
    passwordMismatch: 'Açar sözleri gabat gelmedi',
  },
  en: {
    home: 'Home',
    cart: 'Cart',
    admin: 'Admin',
    settings: 'Settings',
    featured: 'Featured',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    description: 'Description',
    delivery: 'Delivery',
    price: 'Price',
    total: 'Total',
    checkout: 'Checkout',
    contact: 'Contact',
    language: 'Language',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    update: 'Update',
    cancel: 'Cancel',
    title: 'Title',
    image: 'Image',
    category: 'Category',
    save: 'Save',
    delete: 'Delete',
    days: 'days',
    orderHistory: 'Order History',
    emptyCart: 'Your cart is empty',
    uploadPhoto: 'Upload Photo',
    orUrl: 'Or image URL',
    adminPanel: 'Admin Panel',
    products: 'Products',
    orders: 'Orders',
    images: 'Images',
    sizes: 'Sizes / Variants',
    addSize: 'Add Size',
    selectSize: 'Select Size',
    selectCategory: 'Select Category',
    sizeRequired: 'Please select a size',
    shippingRates: 'Shipping Rates',
    airCargo: 'Air Cargo (Howa) 7-15 days',
    roadCargo: 'Road Cargo (Gara) 25-30 days',
    expressCargo: 'Express Air 5-7 days',
    contactUs: 'Contact Us',
    orderVia: 'Order via',
    followUs: 'Follow us',
    personalAccount: 'Personal Account',
    copyNumber: 'Copy Number',
    copied: 'Copied!',
    status: 'Status',
    date: 'Date',
    items: 'Items',
    noOrders: 'No orders yet',
    orderDetails: 'Order Details',
    myOrders: 'My Orders',
    trackOrder: 'Track Order',
    st_pending: 'Ordered',
    st_processing: 'In Beijing Warehouse',
    st_shipped: 'Shipped',
    st_arrived: 'Arrived in TM',
    st_delivered: 'Delivered',
    updateStatus: 'Update Status',
    weight: 'Weight',
    shippingCost: 'Shipping Cost',
    enterWeightPrice: 'Enter Weight & Price',
    productTotal: 'Product Total',
    grandTotal: 'Grand Total',
    kg: 'kg',
    setDetails: 'Set Details',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    phone: 'Phone Number',
    email: 'Email',
    fullName: 'Full Name',
    customerID: 'Customer ID',
    welcome: 'Welcome',
    adminLogin: 'Admin Login',
    customerLogin: 'Customer Login',
    loginError: 'Invalid credentials',
    fillAllFields: 'Please fill all fields',
    yourId: 'Your ID',
    enterCustomerId: 'Enter Customer ID (5 digits)',
    createPassword: 'Create a password',
    registrationSuccess: 'Registration Successful!',
    saveYourId: 'Save this ID for logging in:',
    loginToContinue: 'Log In',
    userNotFound: 'User not found',
    sendCode: 'Send Code',
    enterCode: 'Enter Code',
    verify: 'Verify',
    wrongCode: 'Invalid Code',
    codeSentTo: 'Code sent to:',
    resend: 'Resend',
    confirmPassword: 'Confirm Password',
    passwordMismatch: 'Passwords do not match',
  }
};

export const CATEGORIES = [
  'Geyim / Clothing',
  'Aýakgap / Shoes',
  'Elektronika / Electronics',
  'Öý goşlary / Home',
  'Sport / Sport',
  'Gözellik / Beauty',
  'Çagalar üçin / Kids',
  'Aksessuarlar / Accessories',
  'Başga / Other'
];

export const INITIAL_PRODUCTS: Product[] = [];